---
title: "Helpful Resources"
format: html
---

This page contains links to resources that may be helpful for the course.
If you have a resource that you think would be helpful to others, please let me know and I will add it to the list.

## Julia

There are lots of great resources on programming and Julia.
Here is a curated list of some particularly helpful tools.

::: {.callout-note}
Some of these tutorials provide their own instructions on how to install Julia.
Please follow the instructions provided in lab 1.
:::

### Getting Started

* [Julia for Nervous Begineers](https://juliaacademy.com/p/julia-programming-for-nervous-beginners): A free course on JuliaAcademy for people who are hesitant but curious about learning to write code in Julia. 
* [FastTrack to Julia cheatsheet](https://juliadocs.github.io/Julia-Cheat-Sheet/)
* [Comprehensive Julia Tutorials](https://www.youtube.com/playlist?list=PLCXbkShHt01seTlnlVg6O7f6jKGTguFi7): YouTube playlist covering a variety of Julia topics, starting with an introduciton to the language.
* [Matlab-Python-Julia Cheatsheet](https://cheatsheets.quantecon.org/)

### Digging Deeper

* [Introduction to Computational Thinking](https://computationalthinking.mit.edu/Spring21/): a great Julia-based course at MIT covering applied mathematics and computational thinking

### Plotting and Visualization

* [Makie Tutorials](https://docs.makie.org/stable/tutorials/)

## Other Software Tools

### Git and GitHub

* [Version Control](https://missing.csail.mit.edu/2020/version-control/) from MIT's "CS: Your Missing Semester" course.
* [Git and GitHub for Poets](https://www.youtube.com/playlist?list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV): YouTube playlist covering the basics of git and GitHub.
* [Version Control with Git](https://swcarpentry.github.io/git-novice/) course from Software Carpentry


### Zotero

* [Zotero and Citation Management](https://fondrenlearning.blogs.rice.edu/zotero/) by Fondren library
* [Zotero Quick Start Guide](https://www.zotero.org/support/quick_start_guide)
* The [Better BiBTeX](https://retorque.re/zotero-better-bibtex/) extension can be very helpful for exporting references in a format compatible with Quarto

### Typesetting Math

* [Justin Bois' tutorial](http://chebe163.caltech.edu/2018w/handouts/intro_to_latex.html).
* [Markdown Cheatsheet](https://www.markdownguide.org/cheat-sheet/)
* [LaTeX Cheatsheet](https://ctan.math.washington.edu/tex-archive/info/undergradmath/undergradmath.pdf)
* [Mathpix Snip](https://mathpix.com/snip) allows you to convert images of equations to LaTeX code (there is a free tier)
* [Detexify](https://detexify.kirelabs.org/classify.html) lets you draw a symbol and suggests the LaTeX code for the corresponding symbol 
