---
title: "Week 11 Reading"
subtitle: "Sequential Decision Making"
status: published

format:
  html: default
  typst: default
---


## Overview

@garner_slrise:2018 and @deneufville_parkinggarage:2006

Please note that **there is an error in @garner_slrise:2018**; the units of storm surge are off by a factor of 10.
Watch out for your unit conversions!
This means that sea-level rise is emphasized relative to storm surge in the model.
Regardless, the methods and qualitative findings are interesting.

## Discussion Questions

These questions refer to @deneufville_parkinggarage:2006.

1. What are the key takeaways from the three-step analysis presented in Table 3, particularly when comparing the strategies of "Build Small, Expand Later" versus "Build Big Now"?

2. Should designers and engineers prioritize maximizing expected profit or minimizing financial risk when making infrastructure decisions?
   What is your opinion?
   What are your supporting arguments on that?

3. What other types of infrastructure projects could benefit from a simplified spreadsheet-based decision analysis approach, beyond the parking garage example presented in the paper?

4. What are the potential tradeoffs associated with incorporating flexibility into infrastructure design (e.g., higher initial costs, delays, operational complexity)?

5. Under what conditions does flexibility (e.g., phased expansion) lose its value or become ineffective?
   Can you think of any real-world examples where flexibility may not be beneficial?
